// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Products.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260918220528_ReseedCatalog")]
    partial class ReseedCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Products")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "Products");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage", "Products");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "Products");
                });

            modelBuilder.Entity("Modules.Products.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 1000L, null, null, null, null, null);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products", "Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Apple iPhone 15 Pro",
                            Price = 2799.0
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 2599.0
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Simsiz Qulaqlıq AirPods Pro 2",
                            Price = 499.0
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Samsung 55\" 4K Smart TV",
                            Price = 1299.0
                        },
                        new
                        {
                            Id = 201,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Noutbuk Asus ROG Strix G16",
                            Price = 3499.0
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "MacBook Air M3",
                            Price = 2699.0
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Mexaniki Klaviatura Logitech G Pro",
                            Price = 229.0
                        },
                        new
                        {
                            Id = 204,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Simsiz Siçan Logitech MX Master 3S",
                            Price = 189.0
                        },
                        new
                        {
                            Id = 301,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Kişi Qış Gödəkcəsi",
                            Price = 189.5
                        },
                        new
                        {
                            Id = 302,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Qadın Yay Donu",
                            Price = 85.0
                        },
                        new
                        {
                            Id = 303,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Kişi Klassik Köynək",
                            Price = 59.899999999999999
                        },
                        new
                        {
                            Id = 304,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Unisex Hudi",
                            Price = 74.0
                        },
                        new
                        {
                            Id = 401,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Nike Air Max 270",
                            Price = 279.0
                        },
                        new
                        {
                            Id = 402,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Adidas Ultraboost Light",
                            Price = 329.0
                        },
                        new
                        {
                            Id = 403,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Kişi Dəri Çəkmə",
                            Price = 219.0
                        },
                        new
                        {
                            Id = 404,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Qadın Klassik Tufli",
                            Price = 139.0
                        },
                        new
                        {
                            Id = 501,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Ortopedik Matras 160x200",
                            Price = 649.0
                        },
                        new
                        {
                            Id = 502,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "İş Masası",
                            Price = 249.0
                        },
                        new
                        {
                            Id = 503,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Ergonomik Ofis Kreslosu",
                            Price = 389.0
                        },
                        new
                        {
                            Id = 504,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Üçnəfərlik Divan",
                            Price = 1199.0
                        },
                        new
                        {
                            Id = 601,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Tefal Qeyri-yapışqan Tava Dəsti",
                            Price = 159.0
                        },
                        new
                        {
                            Id = 602,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Philips Airfryer XL",
                            Price = 349.0
                        },
                        new
                        {
                            Id = 603,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "De'Longhi Qəhvə Maşını",
                            Price = 899.0
                        },
                        new
                        {
                            Id = 604,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Bıçaq Dəsti (6 ədəd)",
                            Price = 119.0
                        },
                        new
                        {
                            Id = 701,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Qaçış Trenajoru",
                            Price = 1450.0
                        },
                        new
                        {
                            Id = 702,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Futbol Topu Nike Strike",
                            Price = 65.0
                        },
                        new
                        {
                            Id = 703,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Yoqa Xalçası",
                            Price = 45.0
                        },
                        new
                        {
                            Id = 704,
                            CategoryId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Tənzimlənən Hantel Dəsti 2x20 kq",
                            Price = 299.0
                        },
                        new
                        {
                            Id = 801,
                            CategoryId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Clean Code — Robert C. Martin",
                            Price = 49.0
                        },
                        new
                        {
                            Id = 802,
                            CategoryId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Designing Data-Intensive Applications",
                            Price = 69.0
                        },
                        new
                        {
                            Id = 803,
                            CategoryId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Səfillər — Viktor Hüqo",
                            Price = 29.0
                        },
                        new
                        {
                            Id = 804,
                            CategoryId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsVip = false,
                            Name = "Atomik Vərdişlər — Ceyms Klir",
                            Price = 25.0
                        });
                });

            modelBuilder.Entity("Modules.Products.Domain.ProductDescription", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProductDescriptions", "Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.1 düymlük Super Retina XDR ekran, A17 Pro çip, 256 GB yaddaş və titan korpus.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.8 düymlük Dynamic AMOLED ekran, 200 MP kamera, S Pen dəstəyi və 512 GB yaddaş.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Aktiv səs-küy söndürmə, məkan səsi, MagSafe şarj qutusu ilə 30 saata qədər işləmə.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "55 düymlük Crystal UHD ekran, HDR10+, Tizen əməliyyat sistemi, Wi-Fi və Bluetooth.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 201,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Intel Core i9, RTX 4070, 16 GB RAM, 1 TB SSD və 165 Hz ekran — oyun və montaj üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 202,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "13.6 düymlük Liquid Retina ekran, Apple M3 çip, 8 GB RAM, 256 GB SSD, 18 saat batareya.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 203,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "GX Blue açarları, RGB işıqlandırma, çıxarıla bilən kabel və kompakt TKL dizayn.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 204,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "8000 DPI sensor, səssiz düymələr, 3 cihaza qoşulma və USB-C ilə sürətli şarj.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 301,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Su keçirməyən parça, isti astar və kapüşon; -20°C-yə qədər istiliyi saxlayır.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 302,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yüngül pambıq parça, çiçək naxışı, diz uzunluğunda — gündəlik geyim və tətil üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 303,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "100% pambıq, slim fit kəsim, ütü tələb etməyən parça, ağ rəng.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 304,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Yumşaq flis daxili hissə, kenquru cibi, oversize kəsim, 5 rəng seçimi.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 401,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Böyük Air yastıqlı daban və nəfəs alan tor üst hissə — gün boyu rahatlıq.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 402,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Boost köpük altlıq və Primeknit üst hissə — qaçış və gündəlik istifadə üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 403,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Təbii dəri, sürüşməyən altlıq və isti astar — qış mövsümü üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 404,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Lak dəri, 7 sm daban, yumşaq içlik — ofis və tədbirlər üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 501,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müstəqil yay bloku, memory foam üst qat, orta sərtlik və 10 il zəmanət.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 502,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "120x60 sm iş səthi, metal ayaqlar və kabel kanalı — ev ofisi üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 503,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Bel dəstəyi, tənzimlənən qoltuqaltı və hündürlük, nəfəs alan tor arxalıq.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 504,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Velvet üzlük, yumşaq oturacaq, bərk ağac karkas, boz rəng.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 601,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3 tava (20/24/28 sm), titan örtük, induksiya daxil bütün plitələrə uyğun.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 602,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6.2 litr tutum, yağsız qızartma, 7 hazır proqram və asan təmizlənən səbət.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 603,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Avtomatik espresso, daxili dəyirman, süd köpükləndirici və 15 bar təzyiq.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 604,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Paslanmayan polad, ergonomik dəstək və taxta altlıq.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 701,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "3 HP mühərrik, 18 km/saat sürət, 12 hazır proqram və qatlana bilən konstruksiya.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 702,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "FIFA Quality standartı, 5 ölçü, möhkəm rezin kamera — bütün meydançalar üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 703,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "6 mm qalınlıq, sürüşməyən səth, TPE material və daşıma kəməri.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 704,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tez dəyişən disklər, xrom qolluqlar və saxlama qutusu — ev məşqləri üçün.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 801,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Təmiz, oxunaqlı və asan saxlanılan kod yazmaq haqqında klassik kitab.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 802,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Paylanmış sistemlər, verilənlər bazaları və miqyaslama haqqında dərin bələdçi.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 803,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dünya ədəbiyyatının şah əsərlərindən biri, Azərbaycan dilində tam nəşr.",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 804,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kiçik vərdişlərlə böyük nəticələr əldə etməyin praktik yolları.",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Modules.Products.Domain.ProductPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("NewPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("OldPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPriceHistories", "Products");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Modules.Products.Domain.ProductDescription", b =>
                {
                    b.HasOne("Modules.Products.Domain.Product", "Product")
                        .WithOne("ProductDescription")
                        .HasForeignKey("Modules.Products.Domain.ProductDescription", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Products.Domain.ProductPriceHistory", b =>
                {
                    b.HasOne("Modules.Products.Domain.Product", "Product")
                        .WithMany("ProductPriceHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Products.Domain.Product", b =>
                {
                    b.Navigation("ProductDescription");

                    b.Navigation("ProductPriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
